# Analisando o modelo de Churn
* Testando possíveis causas de erros.
---

**Autor(a):** Sabrina Bruni de Souza Faria

## Importando as Bibliotecas

In [1]:
import pandas as pd
import csv
from funcoesAuxiliares import *

## Leitura dos Dados

In [2]:
# Tabela de zeros e uns de todos os períodos do dataset análisado #
dftabTreino = pd.read_csv('Arquivos/tabelaTreinoTrans.csv', index_col=0)
dftabTeste = pd.read_csv('Arquivos/tabelaTesteTrans.csv', index_col=0)

In [3]:
dfC = pd.read_csv('Arquivos/churnResultadoTrans.csv', index_col=0)
dfC.head(5)

,churnLinear,churnExponencial_2,churnExponencial_e,churnRecente,Media_Intervalos
id,,,,,
2378,0.219614,0.213987,0.177926,0.205503,1.397196
576,0.227908,0.403577,0.443411,0.238262,1.648352
704,0.193946,0.398994,0.480849,0.189747,1.339286
3818,0.215486,0.377619,0.455089,0.207569,1.415094
1972,0.233176,0.351865,0.414708,0.234357,1.563158

In [4]:
df = pd.read_csv('Arquivos/TesteTreinoChurnAjustadoTrans.csv')
df.head(5)

,id_cliente,churnLinear,churnExponencial_2,churnExponencial_e,churnRecente,resultado
0,2378,0.0,0.0,0.0,0.0,0.0
1,576,0.0,0.0,0.0,0.0,0.0
2,704,0.0,0.0,0.0,0.0,0.0
3,3818,0.0,0.0,0.0,0.0,0.0
4,1972,0.0,0.0,0.0,0.0,0.0

## Testando

In [5]:
linear = df[df["churnLinear"] != df["resultado"]]
linear = linear[linear["resultado"] == 1]
indices = linear["id_cliente"]

In [6]:
pd.set_option('display.max_columns', None)  # Defina como None para mostrar todas as colunas

In [7]:
tabTes = dftabTeste.loc[indices]
tabTes.iloc[0:5]

,1998-10-23,1998-10-30,1998-11-06,1998-11-13,1998-11-20,1998-11-27,1998-12-04,1998-12-11,1998-12-18,1998-12-25
459,0,0,0,0,0,0,0,0,0,0
7203,1,1,0,0,1,0,0,0,0,0
9591,0,1,0,0,0,1,0,0,0,0
3888,0,0,0,0,0,0,0,0,0,0
2029,0,0,0,0,0,0,0,0,0,0

In [8]:
tabTre = dftabTreino.loc[indices]
tabTre.iloc[0:5]

,1993-01-01,1993-01-08,1993-01-15,1993-01-22,1993-01-29,1993-02-05,1993-02-12,1993-02-19,1993-02-26,1993-03-05,1993-03-12,1993-03-19,1993-03-26,1993-04-02,1993-04-09,1993-04-16,1993-04-23,1993-04-30,1993-05-07,1993-05-14,1993-05-21,1993-05-28,1993-06-04,1993-06-11,1993-06-18,1993-06-25,1993-07-02,1993-07-09,1993-07-16,1993-07-23,1993-07-30,1993-08-06,1993-08-13,1993-08-20,1993-08-27,1993-09-03,1993-09-10,1993-09-17,1993-09-24,1993-10-01,1993-10-08,1993-10-15,1993-10-22,1993-10-29,1993-11-05,1993-11-12,1993-11-19,1993-11-26,1993-12-03,1993-12-10,1993-12-17,1993-12-24,1993-12-31,1994-01-07,1994-01-14,1994-01-21,1994-01-28,1994-02-04,1994-02-11,1994-02-18,1994-02-25,1994-03-04,1994-03-11,1994-03-18,1994-03-25,1994-04-01,1994-04-08,1994-04-15,1994-04-22,1994-04-29,1994-05-06,1994-05-13,1994-05-20,1994-05-27,1994-06-03,1994-06-10,1994-06-17,1994-06-24,1994-07-01,1994-07-08,1994-07-15,1994-07-22,1994-07-29,1994-08-05,1994-08-12,1994-08-19,1994-08-26,1994-09-02,1994-09-09,1994-09-16,1994-09-23,1994-09-30,1994-10-07,1994-10-14,1994-10-21,1994-10-28,1994-11-04,1994-11-11,1994-11-18,1994-11-25,1994-12-02,1994-12-09,1994-12-16,1994-12-23,1994-12-30,1995-01-06,1995-01-13,1995-01-20,1995-01-27,1995-02-03,1995-02-10,1995-02-17,1995-02-24,1995-03-03,1995-03-10,1995-03-17,1995-03-24,1995-03-31,1995-04-07,1995-04-14,1995-04-21,1995-04-28,1995-05-05,1995-05-12,1995-05-19,1995-05-26,1995-06-02,1995-06-09,1995-06-16,1995-06-23,1995-06-30,1995-07-07,1995-07-14,1995-07-21,1995-07-28,1995-08-04,1995-08-11,1995-08-18,1995-08-25,1995-09-01,1995-09-08,1995-09-15,1995-09-22,1995-09-29,1995-10-06,1995-10-13,1995-10-20,1995-10-27,1995-11-03,1995-11-10,1995-11-17,1995-11-24,1995-12-01,1995-12-08,1995-12-15,1995-12-22,1995-12-29,1996-01-05,1996-01-12,1996-01-19,1996-01-26,1996-02-02,1996-02-09,1996-02-16,1996-02-23,1996-03-01,1996-03-08,1996-03-15,1996-03-22,1996-03-29,1996-04-05,1996-04-12,1996-04-19,1996-04-26,1996-05-03,1996-05-10,1996-05-17,1996-05-24,1996-05-31,1996-06-07,1996-06-14,1996-06-21,1996-06-28,1996-07-05,1996-07-12,1996-07-19,1996-07-26,1996-08-02,1996-08-09,1996-08-16,1996-08-23,1996-08-30,1996-09-06,1996-09-13,1996-09-20,1996-09-27,1996-10-04,1996-10-11,1996-10-18,1996-10-25,1996-11-01,1996-11-08,1996-11-15,1996-11-22,1996-11-29,1996-12-06,1996-12-13,1996-12-20,1996-12-27,1997-01-03,1997-01-10,1997-01-17,1997-01-24,1997-01-31,1997-02-07,1997-02-14,1997-02-21,1997-02-28,1997-03-07,1997-03-14,1997-03-21,1997-03-28,1997-04-04,1997-04-11,1997-04-18,1997-04-25,1997-05-02,1997-05-09,1997-05-16,1997-05-23,1997-05-30,1997-06-06,1997-06-13,1997-06-20,1997-06-27,1997-07-04,1997-07-11,1997-07-18,1997-07-25,1997-08-01,1997-08-08,1997-08-15,1997-08-22,1997-08-29,1997-09-05,1997-09-12,1997-09-19,1997-09-26,1997-10-03,1997-10-10,1997-10-17,1997-10-24,1997-10-31,1997-11-07,1997-11-14,1997-11-21,1997-11-28,1997-12-05,1997-12-12,1997-12-19,1997-12-26,1998-01-02,1998-01-09,1998-01-16,1998-01-23,1998-01-30,1998-02-06,1998-02-13,1998-02-20,1998-02-27,1998-03-06,1998-03-13,1998-03-20,1998-03-27,1998-04-03,1998-04-10,1998-04-17,1998-04-24,1998-05-01,1998-05-08,1998-05-15,1998-05-22,1998-05-29,1998-06-05,1998-06-12,1998-06-19,1998-06-26,1998-07-03,1998-07-10,1998-07-17,1998-07-24,1998-07-31,1998-08-07,1998-08-14,1998-08-21,1998-08-28,1998-09-04,1998-09-11,1998-09-18,1998-09-25,1998-10-02,1998-10-09,1998-10-16
459,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7203,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,0,1,1,0,0,1,1,0,0,1,0,1,0,1,0,1,0,0,1,1,0,0,1,1,0,0,1,1,1,0,0,1,1,1,0,1,1,1,0,1,0,1,1,1,1,1,0,1,1,0,1,0,1,0,1,1,1,0,1,0,0,1,1,1,1,1,1,1,0,1,0,1,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,1,1,1,1,0,1,0,1,0,1,0,1,0,0,1,1,0,1,1,0,1,0,1,0,1,0,1,1,1,1,1,1,0,1,0,1,0,1,0,0,1,1,0,1,1,1,0,0,0,1,1,1,0,1,1,1,0,1,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,1,0,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,1,1,0,0,1,1,0,0,0,1,0,0,0
9591,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,0,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,0,0,1,1,0,0,1,1,1,0,1,0,1,0,0,1,1,0,0,1,1,1,0,1,1,1,0,0,1,1,0,0,1,1,1,0,1,1,1,0,0,1,1,1,1,1,1,1,0,1,1,1,0,0,1,1,1,0,1,1,1,0,0,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,0,1,1,1,1,0,1,0,1,0,0,1,1,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,0,1,0,1,1,1,1,1,0,1,1,1,0,0,1,0,1,0,0,1,1,0,0,1,1,1,1,1,0,1,1,1,0,1,0,0,1,1,0,1,1,0,1,1,0,1,1,0,0,1,1,0,0,1,0,1,0
3888,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2029,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
churn = dfC.loc[dfC.index.isin(indices)]
churn.iloc[0:5]

,churnLinear,churnExponencial_2,churnExponencial_e,churnRecente,Media_Intervalos
id,,,,,
459,0.198072,0.223256,0.223256,0.186912,4.479167
7203,0.267044,0.476988,0.495664,0.251697,1.952381
9591,0.223025,0.490651,0.533436,0.199655,1.375610
3888,0.180986,0.216327,0.216327,0.175049,4.622642
2029,0.176651,0.190217,0.190217,0.165934,5.257143

In [10]:
churnint = df.loc[df['id_cliente'].isin(indices)]
churnint

,id_cliente,churnLinear,churnExponencial_2,churnExponencial_e,churnRecente,resultado
61,459,0.0,0.0,0.0,0.0,1.0
277,7203,0.0,0.0,0.0,0.0,1.0
435,9591,0.0,0.0,0.0,0.0,1.0
459,3888,0.0,0.0,0.0,0.0,1.0
463,2029,0.0,0.0,0.0,0.0,1.0
503,10266,0.0,1.0,1.0,0.0,1.0
636,2732,0.0,0.0,0.0,0.0,1.0
681,1589,0.0,0.0,0.0,0.0,1.0
783,2691,0.0,0.0,0.0,0.0,1.0
800,10036,0.0,0.0,0.0,0.0,1.0
887,799,0.0,0.0,0.0,0.0,1.0
928,2180,0.0,0.0,0.0,0.0,1.0
972,3326,0.0,0.0,0.0,0.0,1.0
1045,4237,0.0,0.0,0.0,0.0,1.0
1235,740,0.0,0.0,0.0,0.0,1.0
1241,761,0.0,0.0,0.0,0.0,1.0
1243,3036,0.0,0.0,0.0,0.0,1.0
1263,31,0.0,0.0,0.0,0.0,1.0
1322,3037,0.0,0.0,0.0,0.0,1.0
1342,4519,0.0,0.0,0.0,0.0,1.0
1435,3797,0.0,0.0,0.0,0.0,1.0
1797,4538,0.0,0.0,0.0,0.0,1.0
1815,1720,0.0,0.0,0.0,0.0,1.0
1837,1974,0.0,0.0,0.0,0.0,1.0
1889,99,0.0,0.0,0.0,0.0,1.0
1980,4258,0.0,0.0,0.0,0.0,1.0
1984,2236,0.0,0.0,0.0,0.0,1.0
2235,3814,0.0,0.0,0.0,0.0,1.0
2520,1028,0.0,0.0,0.0,0.0,1.0
2815,3668,0.0,0.0,0.0,0.0,1.0
2949,869,0.0,0.0,0.0,0.0,1.0
3072,1563,0.0,0.0,0.0,0.0,1.0
3113,182,0.0,0.0,0.0,0.0,1.0
3313,11325,0.0,0.0,0.0,0.0,1.0
3332,1060,0.0,0.0,0.0,0.0,1.0
3382,2130,0.0,0.0,0.0,0.0,1.0
3496,1735,0.0,0.0,0.0,0.0,1.0
3590,1056,0.0,0.0,0.0,0.0,1.0
3630,2300,0.0,0.0,0.0,0.0,1.0
3640,4534,0.0,0.0,0.0,0.0,1.0
3679,2021,0.0,0.0,0.0,0.0,1.0
3705,1430,0.0,0.0,0.0,0.0,1.0
3801,1466,0.0,0.0,0.0,0.0,1.0
3937,2900,0.0,0.0,0.0,0.0,1.0
3951,2698,0.0,0.0,0.0,0.0,1.0
4364,1172,0.0,0.0,0.0,0.0,1.0